version: '3.8'
services:
  tomcat:
    image: tomcat:10
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./target/hometask1-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/hometask1-1.0-SNAPSHOT.war
    restart: on-failure
